---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels: 
{{- toYaml .Values.configmap.labels | trim | nindent 4 }}
data:
{{ toYaml .Values.configmap.data | indent 4 }}
