---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.helloservice.name }}
  labels: {{ toYaml .Values.helloservice.labels | trim | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.helloservice.port }}
    targetPort: {{ .Values.hellodeployment.containerPort }}
    protocol: TCP
  selector: {{ toYaml .Values.hellodeployment.labels | trim | nindent 4 }}